"""NAD T187/T777/T787 command metadata generated from the vendor PDFs."""

from __future__ import annotations

COMMANDS = {'DSP.Version': {'op': '?',
                 'values': [],
                 'range': None,
                 'step': None,
                 'desc': 'Query DSP Version',
                 'models': ['T187', 'T777', 'T787']},
 'Ipod.Album': {'op': '?',
                'values': [],
                'range': None,
                'step': None,
                'desc': 'Get the current playing album name',
                'models': ['T187', 'T777', 'T787']},
 'Ipod.Artist': {'op': '?',
                 'values': [],
                 'range': None,
                 'step': None,
                 'desc': 'Get the current playing track artist',
                 'models': ['T187', 'T777', 'T787']},
 'Ipod.AudiobookSpeed': {'op': '=/+/-/?',
                         'values': ['Slow', 'Normal', 'Fast'],
                         'range': None,
                         'step': None,
                         'desc': 'iPod Audiobook Speed',
                         'models': ['T187', 'T777', 'T787']},
 'Ipod.AutoConnect': {'op': '=/+/-/?',
                      'values': ['No', 'Yes'],
                      'range': None,
                      'step': None,
                      'desc': 'AutoConnect to iPod when iPod source is selected',
                      'models': ['T187', 'T777', 'T787']},
 'Ipod.Enabled': {'op': '=/+/-/?',
                  'values': ['Yes', 'No'],
                  'range': None,
                  'step': None,
                  'desc': 'Enable/Disable the iPod interface',
                  'models': ['T187', 'T777', 'T787']},
 'Ipod.MenuTimeout': {'op': '=/+/-/?',
                      'values': [],
                      'range': [0, 60],
                      'step': 5,
                      'desc': 'Timeout before returning to iPod "Now Playing" scre en',
                      'models': ['T187', 'T777', 'T787']},
 'Ipod.PlayMode': {'op': '=/+/-/?',
                   'values': ['Rewind', 'FastForward', 'Pause', 'Play'],
                   'range': None,
                   'step': None,
                   'desc': 'Set the iPod to Rewind',
                   'models': ['T187', 'T777', 'T787']},
 'Ipod.Repeat': {'op': '=/+/-/?',
                 'values': ['All', 'Off', 'One'],
                 'range': None,
                 'step': None,
                 'desc': 'Set the iPod to Repeat Off, One, or All',
                 'models': ['T187', 'T777', 'T787']},
 'Ipod.Shuffle': {'op': '=/+/-/?',
                  'values': ['Off', 'Albums', 'Songs'],
                  'range': None,
                  'step': None,
                  'desc': 'Set the iPod to Shuffle Off, Songs, or Albums. Not e: must be set '
                          'before selecting music.',
                  'models': ['T187', 'T777', 'T787']},
 'Ipod.Title': {'op': '?',
                'values': [],
                'range': None,
                'step': None,
                'desc': 'Get the current playing track title',
                'models': ['T187', 'T777', 'T787']},
 'Ipod.Track': {'op': '+/-',
                'values': [],
                'range': None,
                'step': None,
                'desc': 'Track Next/Previous',
                'models': ['T187', 'T777', 'T787']},
 'Main.Amp.Back': {'op': '=/+/-/?',
                   'values': ['Zone3', 'Front', 'Zone4', 'Zone2', 'Back'],
                   'range': None,
                   'step': None,
                   'desc': 'Set the back Amplifier output to Zone3',
                   'models': ['T187', 'T777', 'T787']},
 'Main.Audyssey': {'op': '=/+/-/?',
                   'values': ['Audyssey', 'Flat', 'Off', 'NAD'],
                   'range': None,
                   'step': None,
                   'desc': 'Set the Audyssey Curve',
                   'models': ['T187', 'T777', 'T787']},
 'Main.Audyssey.ADV': {'op': '=/+/-/?',
                       'values': ['Off', 'Heavy', 'Medium', 'Light'],
                       'range': None,
                       'step': None,
                       'desc': 'Audyssey Volume (Command Valid with AM200 Only)',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Audyssey.DEQ': {'op': '=/+/-/?',
                       'values': ['Off', 'On'],
                       'range': None,
                       'step': None,
                       'desc': 'Audyssey Dynamic EQ (Command Valid with AM200 Only)',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Audyssey.Offset': {'op': '=/+/-/?',
                          'values': [],
                          'range': [0, 15],
                          'step': 1,
                          'desc': 'Audyssey Dynamic EQ Offset (Command Valid with AM20 0 Only)',
                          'models': ['T187', 'T777', 'T787']},
 'Main.AutoTrigger': {'op': '=/+/-/?',
                      'values': ['Main', 'All', 'Zone4', 'Zone3', 'Zone2'],
                      'range': None,
                      'step': None,
                      'desc': 'Set Trigger Input',
                      'models': ['T187', 'T777', 'T787']},
 'Main.Bass': {'op': '=/+/-/?',
               'values': [],
               'range': [-10, 10],
               'step': 2,
               'desc': 'Set the Bass Tone Control',
               'models': ['T187', 'T777', 'T787']},
 'Main.CEC.Arc': {'op': '=/+/-/?',
                  'values': ['SourceSetup', 'Off', 'Auto'],
                  'range': None,
                  'step': None,
                  'desc': 'Enables selection of ARC in Source Setup OSD Menu',
                  'models': ['T187', 'T777', 'T787']},
 'Main.CEC.Audio': {'op': '=/+/-/?',
                    'values': ['Off', 'On'],
                    'range': None,
                    'step': None,
                    'desc': 'Feature Disabled',
                    'models': ['T187', 'T777', 'T787']},
 'Main.CEC.Power': {'op': '=/+/-/?',
                    'values': ['On', 'Off'],
                    'range': None,
                    'step': None,
                    'desc': 'Allows receiver to be turned on and off via CEC (TXX5 series only '
                            'turns off)',
                    'models': ['T187', 'T777', 'T787']},
 'Main.CEC.Switch': {'op': '=/+/-/?',
                     'values': ['On', 'Off'],
                     'range': None,
                     'step': None,
                     'desc': "Allows CEC to change receiver's source",
                     'models': ['T187', 'T777', 'T787']},
 'Main.CenterDialog': {'op': '=/+/-/?',
                       'values': [],
                       'range': [-6, 6],
                       'step': 2,
                       'desc': 'Set the CenterDialog Tone Control',
                       'models': ['T187', 'T777', 'T787']},
 'Main.ControlStandby': {'op': '=/+/-/?',
                         'values': ['On', 'Off'],
                         'range': None,
                         'step': None,
                         'desc': 'Allow Ethernet control when in standby',
                         'models': ['T187', 'T777', 'T787']},
 'Main.DTS.CenterGain': {'op': '=/+/-/?',
                         'values': ['0', '0.1', '0.2', '0.3', '0.4', '0.5'],
                         'range': None,
                         'step': None,
                         'desc': 'Set DTS Center Gain',
                         'models': ['T187', 'T777', 'T787']},
 'Main.DTS.DRC': {'op': '=/+/-/?',
                  'values': [],
                  'range': [25, 100],
                  'step': 25,
                  'desc': 'Set DTS Dynamic Range Control',
                  'models': ['T187', 'T777', 'T787']},
 'Main.Dimmer': {'op': '=/+/-/?',
                 'values': ['Off', 'On'],
                 'range': None,
                 'step': None,
                 'desc': 'Front VFD Dimmer',
                 'models': ['T187', 'T777', 'T787']},
 'Main.Distance.BackLeft': {'op': '=/+/-/?',
                            'values': [],
                            'range': [0, 30],
                            'step': 1,
                            'desc': 'Set the speaker distance in Feet',
                            'models': ['T187', 'T777', 'T787']},
 'Main.Distance.BackRight': {'op': '=/+/-/?',
                             'values': [],
                             'range': [0, 30],
                             'step': 1,
                             'desc': 'Set the speaker distance in Feet',
                             'models': ['T187', 'T777', 'T787']},
 'Main.Distance.Center': {'op': '=/+/-/?',
                          'values': [],
                          'range': [0, 30],
                          'step': 1,
                          'desc': 'Set the speaker distance in Feet',
                          'models': ['T187', 'T777', 'T787']},
 'Main.Distance.Left': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 30],
                        'step': 1,
                        'desc': 'Set the speaker distance in Feet',
                        'models': ['T187', 'T777', 'T787']},
 'Main.Distance.Right': {'op': '=/+/-/?',
                         'values': [],
                         'range': [0, 30],
                         'step': 1,
                         'desc': 'Set the speaker distance in Feet',
                         'models': ['T187', 'T777', 'T787']},
 'Main.Distance.Sub': {'op': '=/+/-/?',
                       'values': [],
                       'range': [0, 30],
                       'step': 1,
                       'desc': 'Set the speaker distance in Feet',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Distance.SurroundLeft': {'op': '=/+/-/?',
                                'values': [],
                                'range': [0, 30],
                                'step': 1,
                                'desc': 'Set the speaker distance in Feet',
                                'models': ['T187', 'T777', 'T787']},
 'Main.Distance.SurroundRight': {'op': '=/+/-/?',
                                 'values': [],
                                 'range': [0, 30],
                                 'step': 1,
                                 'desc': 'Set the speaker distance in Feet',
                                 'models': ['T187', 'T777', 'T787']},
 'Main.Distance.UOM': {'op': '=/+/-/?',
                       'values': ['Feet', 'Meters'],
                       'range': None,
                       'step': None,
                       'desc': 'Set the Unit of Measurement',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Dolby.CenterWidth': {'op': '=/+/-/?',
                            'values': [],
                            'range': [0, 7],
                            'step': 1,
                            'desc': 'Dolby Center Width',
                            'models': ['T187', 'T777', 'T787']},
 'Main.Dolby.DRC': {'op': '=/+/-/?',
                    'values': [],
                    'range': [25, 100],
                    'step': 25,
                    'desc': 'Dolby Dynamic Range Control (100% is maximum dynami c range)',
                    'models': ['T187', 'T777', 'T787']},
 'Main.Dolby.Dimension': {'op': '=/+/-/?',
                          'values': [],
                          'range': [-7, 7],
                          'step': 1,
                          'desc': 'Dolby Dimension',
                          'models': ['T187', 'T777', 'T787']},
 'Main.Dolby.Panorama': {'op': '=/+/-/?',
                         'values': ['On', 'Off'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Dolby Panorama',
                         'models': ['T187', 'T777', 'T787']},
 'Main.EnhancedBass': {'op': '=/+/-/?',
                       'values': ['Off', 'On'],
                       'range': None,
                       'step': None,
                       'desc': 'Set Enhanced Bass On/Off',
                       'models': ['T187', 'T777', 'T787']},
 'Main.EnhancedStereo.Back': {'op': '=/+/-/?',
                              'values': ['Off', 'On'],
                              'range': None,
                              'step': None,
                              'desc': 'Set Enhanced Stereo Speakers',
                              'models': ['T187', 'T777', 'T787']},
 'Main.EnhancedStereo.Center': {'op': '=/+/-/?',
                                'values': ['Off', 'On'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Enhanced Stereo Speakers',
                                'models': ['T187', 'T777', 'T787']},
 'Main.EnhancedStereo.Front': {'op': '=/+/-/?',
                               'values': ['Off', 'On'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Enhanced Stereo Speakers',
                               'models': ['T187', 'T777', 'T787']},
 'Main.EnhancedStereo.Surround': {'op': '=/+/-/?',
                                  'values': ['On', 'Off'],
                                  'range': None,
                                  'step': None,
                                  'desc': 'Set Enhanced Stereo Speakers',
                                  'models': ['T187', 'T777', 'T787']},
 'Main.IR': {'op': '=',
             'values': [],
             'range': None,
             'step': None,
             'desc': 'Send IR Commands via RS232 where <VALUE> is decimal IR code',
             'models': ['T187', 'T777', 'T787']},
 'Main.IR.Channel': {'op': '=/+/-/?',
                     'values': [],
                     'range': [0, 1],
                     'step': 1,
                     'desc': "Set the Main IR Channel (allows for two NAD's to be controlled "
                             'seperately)',
                     'models': ['T187', 'T777', 'T787']},
 'Main.IR1': {'op': '=',
              'values': [],
              'range': None,
              'step': None,
              'desc': 'String showing the HEX value of a supported IR comm and (0x877C customer '
                      'code)',
              'models': ['T187', 'T777', 'T787']},
 'Main.IR2': {'op': '=',
              'values': [],
              'range': None,
              'step': None,
              'desc': 'String showing the HEX value of a supported IR comm and (0x860F customer '
                      'code)',
              'models': ['T187', 'T777', 'T787']},
 'Main.Level.BackLeft': {'op': '=/+/-/?',
                         'values': [],
                         'range': [-12, 12],
                         'step': 1,
                         'desc': 'Set Speaker Level',
                         'models': ['T187', 'T777', 'T787']},
 'Main.Level.BackRight': {'op': '=/+/-/?',
                          'values': [],
                          'range': [-12, 12],
                          'step': 1,
                          'desc': 'Set Speaker Level',
                          'models': ['T187', 'T777', 'T787']},
 'Main.Level.Center': {'op': '=/+/-/?',
                       'values': [],
                       'range': [-12, 12],
                       'step': 1,
                       'desc': 'Set Speaker Level',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Level.Left': {'op': '=/+/-/?',
                     'values': [],
                     'range': [-12, 12],
                     'step': 1,
                     'desc': 'Set Speaker Level',
                     'models': ['T187', 'T777', 'T787']},
 'Main.Level.Right': {'op': '=/+/-/?',
                      'values': [],
                      'range': [-12, 12],
                      'step': 1,
                      'desc': 'Set Speaker Level',
                      'models': ['T187', 'T777', 'T787']},
 'Main.Level.Sub': {'op': '=/+/-/?',
                    'values': [],
                    'range': [-12, 12],
                    'step': 1,
                    'desc': 'Set Speaker Level',
                    'models': ['T187', 'T777', 'T787']},
 'Main.Level.SurroundLeft': {'op': '=/+/-/?',
                             'values': [],
                             'range': [-12, 12],
                             'step': 1,
                             'desc': 'Set Speaker Level',
                             'models': ['T187', 'T777', 'T787']},
 'Main.Level.SurroundRight': {'op': '=/+/-/?',
                              'values': [],
                              'range': [-12, 12],
                              'step': 1,
                              'desc': 'Set Speaker Level',
                              'models': ['T187', 'T777', 'T787']},
 'Main.LipSyncDelay': {'op': '=/+/-/?',
                       'values': [],
                       'range': [0, 120],
                       'step': 1,
                       'desc': 'Set Lip Sync Delay',
                       'models': ['T187', 'T777', 'T787']},
 'Main.ListeningMode': {'op': '=/+/-/?',
                        'values': ['None',
                                   'PLIIMusic',
                                   'SurroundEX',
                                   'AnalogBypass',
                                   'StereoDownmix',
                                   'EnhancedStereo',
                                   'EARS',
                                   'NEO6Music',
                                   'NEO6Cinema',
                                   'ProLogic',
                                   'PLIIMovie'],
                        'range': None,
                        'step': None,
                        'desc': 'Set Active Listening Mode',
                        'models': ['T187', 'T777', 'T787']},
 'Main.ListeningMode.Analog': {'op': '=/+/-/?',
                               'values': ['None',
                                          'PLIIMusic',
                                          'NEO6Music',
                                          'EARS',
                                          'EnhancedStereo',
                                          'AnalogBypass',
                                          'NEO6Cinema',
                                          'ProLogic',
                                          'PLIIMovie'],
                               'range': None,
                               'step': None,
                               'desc': 'Set default Analog Signal Listening Mode',
                               'models': ['T187', 'T777', 'T787']},
 'Main.ListeningMode.DTS': {'op': '=/+/-/?',
                            'values': ['NEO6Music', 'None', 'StereoDownmix'],
                            'range': None,
                            'step': None,
                            'desc': 'Set default DTS Listening Mode',
                            'models': ['T187', 'T777', 'T787']},
 'Main.ListeningMode.Digital': {'op': '=/+/-/?',
                                'values': ['None',
                                           'EnhancedStereo',
                                           'EARS',
                                           'NEO6Music',
                                           'NEO6Cinema',
                                           'PLIIMusic',
                                           'ProLogic',
                                           'StereoDownmix',
                                           'PLIIMovie'],
                                'range': None,
                                'step': None,
                                'desc': 'Set default Digital Signal Listening Mode',
                                'models': ['T187', 'T777', 'T787']},
 'Main.ListeningMode.DolbyDigital': {'op': '=/+/-/?',
                                     'values': ['SurroundEX',
                                                'PLIIMovie',
                                                'None',
                                                'StereoDownmix',
                                                'PLIIMusic'],
                                     'range': None,
                                     'step': None,
                                     'desc': 'Set default Dolby Digital Listening Mode',
                                     'models': ['T187', 'T777', 'T787']},
 'Main.ListeningMode.DolbyDigital2ch': {'op': '=/+/-/?',
                                        'values': ['PLIIMovie', 'PLIIMusic', 'ProLogic', 'None'],
                                        'range': None,
                                        'step': None,
                                        'desc': 'Set default Dolby Digital 2 channel Listening '
                                                'Mode',
                                        'models': ['T187', 'T777', 'T787']},
 'Main.Model': {'op': '?',
                'values': [],
                'range': None,
                'step': None,
                'desc': 'Query AVR Model',
                'models': ['T187', 'T777', 'T787']},
 'Main.Mute': {'op': '=/+/-/?',
               'values': ['Off', 'On'],
               'range': None,
               'step': None,
               'desc': 'Set Mute',
               'models': ['T187', 'T777', 'T787']},
 'Main.OSD.TempDisplay': {'op': '=/+/-/?',
                          'values': ['On', 'Off'],
                          'range': None,
                          'step': None,
                          'desc': 'Set OSD Temp Display On/Off',
                          'models': ['T187', 'T777', 'T787']},
 'Main.Power': {'op': '=/+/-/?',
                'values': ['Off', 'On'],
                'range': None,
                'step': None,
                'desc': 'Turn the Main Power On/Off',
                'models': ['T187', 'T777', 'T787']},
 'Main.Sleep': {'op': '=/+/-/?',
                'values': [],
                'range': [0, 90],
                'step': 1,
                'desc': 'Set Time before Sleep',
                'models': ['T187', 'T777', 'T787']},
 'Main.Source': {'op': '=/+/-/?',
                 'values': [],
                 'range': [1, 10],
                 'step': 1,
                 'desc': 'Set Main Source',
                 'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Back.Config1': {'op': '=/+/-/?',
                               'values': [],
                               'range': [0, 2],
                               'step': 1,
                               'desc': 'Set Back Speakers to Off, One, or Two speakers',
                               'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Back.Config2': {'op': '=/+/-/?',
                               'values': ['Small', 'Large'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Speaker Size',
                               'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Back.Frequency': {'op': '=/+/-/?',
                                 'values': [],
                                 'range': [40, 200],
                                 'step': 10,
                                 'desc': 'Set Speaker Crossover',
                                 'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Center.Config': {'op': '=/+/-/?',
                                'values': ['Off', 'Small', 'Large'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Speaker Size or Turn Speaker Off',
                                'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Center.Frequency': {'op': '=/+/-/?',
                                   'values': [],
                                   'range': [40, 200],
                                   'step': 10,
                                   'desc': 'Set Speaker Crossover',
                                   'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Front.Config': {'op': '=/+/-/?',
                               'values': ['Small', 'Large'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Speaker Size',
                               'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Front.Frequency': {'op': '=/+/-/?',
                                  'values': [],
                                  'range': [40, 200],
                                  'step': 10,
                                  'desc': 'Set Speaker Crossover',
                                  'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Sub': {'op': '=/+/-/?',
                      'values': ['Off', 'On'],
                      'range': None,
                      'step': None,
                      'desc': 'Set Subwoofer On/Off',
                      'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Surround.Config': {'op': '=/+/-/?',
                                  'values': ['Large', 'Off', 'Small'],
                                  'range': None,
                                  'step': None,
                                  'desc': 'Set Speaker Size or Turn Speaker Off',
                                  'models': ['T187', 'T777', 'T787']},
 'Main.Speaker.Surround.Frequency': {'op': '=/+/-/?',
                                     'values': [],
                                     'range': [40, 200],
                                     'step': 10,
                                     'desc': 'Set Speaker Crossover',
                                     'models': ['T187', 'T777', 'T787']},
 'Main.SpeakerA': {'op': '=/+/-/?',
                   'values': ['Off', 'On'],
                   'range': None,
                   'step': None,
                   'desc': 'Set Speaker A On/Off',
                   'models': ['T777', 'T787']},
 'Main.SpeakerB': {'op': '=/+/-/?',
                   'values': ['Off', 'On'],
                   'range': None,
                   'step': None,
                   'desc': 'Set Speaker B On/Off',
                   'models': ['T777', 'T787']},
 'Main.ToneDefeat': {'op': '=/+/-/?',
                     'values': ['On', 'Off'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Tone Defeat On/Off',
                     'models': ['T187', 'T777', 'T787']},
 'Main.Treble': {'op': '=/+/-/?',
                 'values': [],
                 'range': [-10, 10],
                 'step': 2,
                 'desc': 'Set Treble Tone Control',
                 'models': ['T187', 'T777', 'T787']},
 'Main.Trigger1.Delay': {'op': '=/+/-/?',
                         'values': [],
                         'range': [0, 15],
                         'step': 1,
                         'desc': 'Set Trigger 1 Delay',
                         'models': ['T187', 'T777', 'T787']},
 'Main.Trigger1.Out': {'op': '=/+/-/?',
                       'values': ['Zone3', 'Main', 'Zone2', 'Source', 'Zone4', 'Zone234'],
                       'range': None,
                       'step': None,
                       'desc': 'Set Trigger 1',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Trigger2.Delay': {'op': '=/+/-/?',
                         'values': [],
                         'range': [0, 15],
                         'step': 1,
                         'desc': 'Set Trigger 2 Delay',
                         'models': ['T187', 'T777', 'T787']},
 'Main.Trigger2.Out': {'op': '=/+/-/?',
                       'values': ['Zone4', 'Zone234', 'Zone3', 'Zone2', 'Main', 'Source'],
                       'range': None,
                       'step': None,
                       'desc': 'Set Trigger 2',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Trigger3.Delay': {'op': '=/+/-/?',
                         'values': [],
                         'range': [0, 15],
                         'step': 1,
                         'desc': 'Set Trigger 3 Delay',
                         'models': ['T187', 'T777', 'T787']},
 'Main.Trigger3.Out': {'op': '=/+/-/?',
                       'values': ['Zone2', 'Source', 'Zone234', 'Zone3', 'Main', 'Zone4'],
                       'range': None,
                       'step': None,
                       'desc': 'Set Trigger 3',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Trim.Center': {'op': '=/+/-/?',
                      'values': [],
                      'range': [-6, 6],
                      'step': 1,
                      'desc': 'Set Trim Level (Not saved when receiver power is cycled)',
                      'models': ['T187', 'T777', 'T787']},
 'Main.Trim.Sub': {'op': '=/+/-/?',
                   'values': [],
                   'range': [-6, 6],
                   'step': 1,
                   'desc': 'Set Trim Level (Not saved when receiver power is cycled)',
                   'models': ['T187', 'T777', 'T787']},
 'Main.Trim.Surround': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-6, 6],
                        'step': 1,
                        'desc': 'Set Trim Level (Not saved when receiver power is cycled)',
                        'models': ['T187', 'T777', 'T787']},
 'Main.VFD.Display': {'op': '=/+/-/?',
                      'values': ['Temp', 'On'],
                      'range': None,
                      'step': None,
                      'desc': 'Set VFD Display Temp/On',
                      'models': ['T187', 'T777', 'T787']},
 'Main.VFD.Line1': {'op': '=/+/-/?',
                    'values': ['Volume',
                               'ListeningMode',
                               'MainSource',
                               'AudioSourceFormat',
                               'Zone2Source',
                               'Zone4Source',
                               'Zone3Source',
                               'Off'],
                    'range': None,
                    'step': None,
                    'desc': 'Set VFD Line 1 Item',
                    'models': ['T187', 'T777', 'T787']},
 'Main.VFD.Line2': {'op': '=/+/-/?',
                    'values': ['Off',
                               'Zone4Source',
                               'Zone3Source',
                               'Zone2Source',
                               'AudioSourceFormat',
                               'ListeningMode',
                               'Volume',
                               'MainSource'],
                    'range': None,
                    'step': None,
                    'desc': 'Set VFD Line 2 Item',
                    'models': ['T187', 'T777', 'T787']},
 'Main.VFD.TempLine': {'op': '=/+/-/?',
                       'values': [],
                       'range': [1, 2],
                       'step': 1,
                       'desc': 'Set VFD Time Line to 1 or 2',
                       'models': ['T187', 'T777', 'T787']},
 'Main.Version': {'op': '?',
                  'values': [],
                  'range': None,
                  'step': None,
                  'desc': 'Query Main MCU Version',
                  'models': ['T187', 'T777', 'T787']},
 'Main.Video.Aspect.Mode': {'op': '=/+/-/?',
                            'values': ['Zoom', 'LetterBox', 'Stretch'],
                            'range': None,
                            'step': None,
                            'desc': 'Zome the video output (Command Valid with VM200 Onl y)',
                            'models': ['T187', 'T777', 'T787']},
 'Main.Video.Aspect.Ratio': {'op': '=/+/-/?',
                             'values': ['4:3', '16:9'],
                             'range': None,
                             'step': None,
                             'desc': '(Command Valid with VM200 Only)',
                             'models': ['T187', 'T777', 'T787']},
 'Main.Video.Brightness': {'op': '=/+/-/?',
                           'values': [],
                           'range': [0, 100],
                           'step': 1,
                           'desc': 'Brightness (Command Valid with VM200 Only)',
                           'models': ['T187', 'T777', 'T787']},
 'Main.Video.Contrast': {'op': '=/+/-/?',
                         'values': [],
                         'range': [0, 100],
                         'step': 1,
                         'desc': 'Contrast (Command Valid with VM200 Only)',
                         'models': ['T187', 'T777', 'T787']},
 'Main.Video.EdgeEnhancement.Level': {'op': '=/+/-/?',
                                      'values': [],
                                      'range': [0, 100],
                                      'step': 1,
                                      'desc': 'Edge Enhacement (Command Valid with VM200 Only)',
                                      'models': ['T187', 'T777', 'T787']},
 'Main.Video.EdgeEnhancement.Treshold': {'op': '=/+/-/?',
                                         'values': [],
                                         'range': [0, 100],
                                         'step': 1,
                                         'desc': 'Edge Enhacement (Command Valid with VM200 Only)',
                                         'models': ['T187', 'T777', 'T787']},
 'Main.Video.NoiseReduction': {'op': '=/+/-/?',
                               'values': [],
                               'range': [0, 50],
                               'step': 1,
                               'desc': 'Noise Reduction (Command Valid with VM200 Only)',
                               'models': ['T187', 'T777', 'T787']},
 'Main.Video.Rate': {'op': '=/+/-/?',
                     'values': ['60', '50'],
                     'range': None,
                     'step': None,
                     'desc': '(Command Valid with VM200 Only)',
                     'models': ['T187', 'T777', 'T787']},
 'Main.Video.Resolution': {'op': '=/+/-/?',
                           'values': ['576p', '1080p', '576i', '480i', '480p', '720p', '1080i'],
                           'range': None,
                           'step': None,
                           'desc': 'Video Resolution (Command Valid with VM200 Only)',
                           'models': ['T187', 'T777', 'T787']},
 'Main.VideoMode': {'op': '=/+/-/?',
                    'values': ['NTSC', 'PAL'],
                    'range': None,
                    'step': None,
                    'desc': 'Set Main Video Mode',
                    'models': ['T187', 'T777', 'T787']},
 'Main.Volume': {'op': '=/+/-/?',
                 'values': [],
                 'range': [-99, 19],
                 'step': 1,
                 'desc': 'Set Main Volume (range depends on levels, trims, et c)',
                 'models': ['T187', 'T777', 'T787']},
 'Preset1.Setup.DSPOptions': {'op': '=/+/-/?',
                              'values': ['Yes', 'No'],
                              'range': None,
                              'step': None,
                              'desc': 'Set Preset to include DSP Options',
                              'models': ['T187', 'T777', 'T787']},
 'Preset1.Setup.Display': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Display settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset1.Setup.ListeningMode': {'op': '=/+/-/?',
                                 'values': ['Yes', 'No'],
                                 'range': None,
                                 'step': None,
                                 'desc': 'Set Preset to include Listening Mode Options',
                                 'models': ['T187', 'T777', 'T787']},
 'Preset1.Setup.PictureControls': {'op': '=/+/-/?',
                                   'values': ['Yes', 'No'],
                                   'range': None,
                                   'step': None,
                                   'desc': '(Command Valid with VM200 Only)',
                                   'models': ['T187', 'T777', 'T787']},
 'Preset1.Setup.Speaker': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Speaker Settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset1.Setup.ToneControls': {'op': '=/+/-/?',
                                'values': ['Yes', 'No'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Preset to include Tone Control Settings',
                                'models': ['T187', 'T777', 'T787']},
 'Preset2.Setup.DSPOptions': {'op': '=/+/-/?',
                              'values': ['No', 'Yes'],
                              'range': None,
                              'step': None,
                              'desc': 'Set Preset to not include DSP Options',
                              'models': ['T187', 'T777', 'T787']},
 'Preset2.Setup.Display': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Display settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset2.Setup.ListeningMode': {'op': '=/+/-/?',
                                 'values': ['Yes', 'No'],
                                 'range': None,
                                 'step': None,
                                 'desc': 'Set Preset to include Listening Mode Options',
                                 'models': ['T187', 'T777', 'T787']},
 'Preset2.Setup.PictureControls': {'op': '=/+/-/?',
                                   'values': ['Yes', 'No'],
                                   'range': None,
                                   'step': None,
                                   'desc': '(Command Valid with VM200 Only)',
                                   'models': ['T187', 'T777', 'T787']},
 'Preset2.Setup.Speaker': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Speaker Settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset2.Setup.ToneControls': {'op': '=/+/-/?',
                                'values': ['Yes', 'No'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Preset to include Tone Control Settings',
                                'models': ['T187', 'T777', 'T787']},
 'Preset3.Setup.DSPOptions': {'op': '=/+/-/?',
                              'values': ['No', 'Yes'],
                              'range': None,
                              'step': None,
                              'desc': 'Set Preset to not include DSP Options',
                              'models': ['T187', 'T777', 'T787']},
 'Preset3.Setup.Display': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Display settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset3.Setup.ListeningMode': {'op': '=/+/-/?',
                                 'values': ['Yes', 'No'],
                                 'range': None,
                                 'step': None,
                                 'desc': 'Set Preset to include Listening Mode Options',
                                 'models': ['T187', 'T777', 'T787']},
 'Preset3.Setup.PictureControls': {'op': '=/+/-/?',
                                   'values': ['No', 'Yes'],
                                   'range': None,
                                   'step': None,
                                   'desc': '(Command Valid with VM200 Only)',
                                   'models': ['T187', 'T777', 'T787']},
 'Preset3.Setup.Speaker': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Speaker Settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset3.Setup.ToneControls': {'op': '=/+/-/?',
                                'values': ['Yes', 'No'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Preset to include Tone Control Settings',
                                'models': ['T187', 'T777', 'T787']},
 'Preset4.Setup.DSPOptions': {'op': '=/+/-/?',
                              'values': ['No', 'Yes'],
                              'range': None,
                              'step': None,
                              'desc': 'Set Preset to not include DSP Options',
                              'models': ['T187', 'T777', 'T787']},
 'Preset4.Setup.Display': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Display settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset4.Setup.ListeningMode': {'op': '=/+/-/?',
                                 'values': ['No', 'Yes'],
                                 'range': None,
                                 'step': None,
                                 'desc': 'Set Preset to not include Listening Mode Options',
                                 'models': ['T187', 'T777', 'T787']},
 'Preset4.Setup.PictureControls': {'op': '=/+/-/?',
                                   'values': ['No', 'Yes'],
                                   'range': None,
                                   'step': None,
                                   'desc': '(Command Valid with VM200 Only)',
                                   'models': ['T187', 'T777', 'T787']},
 'Preset4.Setup.Speaker': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Speaker Settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset4.Setup.ToneControls': {'op': '=/+/-/?',
                                'values': ['Yes', 'No'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Preset to include Tone Control Settings',
                                'models': ['T187', 'T777', 'T787']},
 'Preset5.Setup.DSPOptions': {'op': '=/+/-/?',
                              'values': ['No', 'Yes'],
                              'range': None,
                              'step': None,
                              'desc': 'Set Preset to not include DSP Options',
                              'models': ['T187', 'T777', 'T787']},
 'Preset5.Setup.Display': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Display settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset5.Setup.ListeningMode': {'op': '=/+/-/?',
                                 'values': ['No', 'Yes'],
                                 'range': None,
                                 'step': None,
                                 'desc': 'Set Preset to not include Listening Mode Options',
                                 'models': ['T187', 'T777', 'T787']},
 'Preset5.Setup.PictureControls': {'op': '=/+/-/?',
                                   'values': ['No', 'Yes'],
                                   'range': None,
                                   'step': None,
                                   'desc': '(Command Valid with VM200 Only)',
                                   'models': ['T187', 'T777', 'T787']},
 'Preset5.Setup.Speaker': {'op': '=/+/-/?',
                           'values': ['No', 'Yes'],
                           'range': None,
                           'step': None,
                           'desc': 'Set Preset to not include Speaker Settings',
                           'models': ['T187', 'T777', 'T787']},
 'Preset5.Setup.ToneControls': {'op': '=/+/-/?',
                                'values': ['No', 'Yes'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Preset to not include Tone Control Settings',
                                'models': ['T187', 'T777', 'T787']},
 'Source1.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Off', '7.1', 'Stereo'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source1.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source1.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source1.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['ARC', 'HDMI', 'Coaxial', 'Optical', 'Off'],
                                'range': None,
                                'step': None,
                                'desc': "Set source's digital audio to HDMI's audio return c "
                                        'hannel (ARC)',
                                'models': ['T187', 'T777', 'T787']},
 'Source1.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source1.Enabled': {'op': '=/+/-/?',
                     'values': ['Yes', 'No'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source1.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source1.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source1.VideoFormat': {'op': '=/+/-/?',
                         'values': ['Video', 'SVideo', 'Component', 'HDMI', 'Off'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source1.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source10.AnalogAudioFormat': {'op': '=/+/-/?',
                                'values': ['Stereo'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Analog Audio Format',
                                'models': ['T187', 'T777', 'T787']},
 'Source10.AnalogAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [9, 9],
                               'step': 0,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source10.AnalogGain': {'op': '=/+/-/?',
                         'values': [],
                         'range': [-12, 12],
                         'step': 3,
                         'desc': 'Set Analog Audio Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source10.DigitalAudioFormat': {'op': '=/+/-/?',
                                 'values': ['Coaxial', 'ARC', 'HDMI', 'Optical', 'Off'],
                                 'range': None,
                                 'step': None,
                                 'desc': 'Set Digital Audio Format',
                                 'models': ['T187', 'T777', 'T787']},
 'Source10.DigitalAudioInput': {'op': '=/+/-/?',
                                'values': [],
                                'range': [1, 8],
                                'step': 1,
                                'desc': 'Set Digital Audio Input',
                                'models': ['T187', 'T777', 'T787']},
 'Source10.Enabled': {'op': '=/+/-/?',
                      'values': ['Yes'],
                      'range': None,
                      'step': None,
                      'desc': 'Set Enabled Yes',
                      'models': ['T187', 'T777', 'T787']},
 'Source10.Preset': {'op': '=/+/-/?',
                     'values': [],
                     'range': [0, 5],
                     'step': 1,
                     'desc': 'Set Source Preset',
                     'models': ['T187', 'T777', 'T787']},
 'Source10.TriggerOut': {'op': '=/+/-/?',
                         'values': [],
                         'range': [0, 7],
                         'step': 1,
                         'desc': 'Set Source Trigger Out',
                         'models': ['T187', 'T777', 'T787']},
 'Source10.VideoFormat': {'op': '=/+/-/?',
                          'values': ['Off', 'Video', 'SVideo', 'Component', 'HDMI'],
                          'range': None,
                          'step': None,
                          'desc': 'Set Video Format',
                          'models': ['T187', 'T777', 'T787']},
 'Source10.VideoInput': {'op': '=/+/-/?',
                         'values': [],
                         'range': [1, 8],
                         'step': 1,
                         'desc': 'Set Video Input',
                         'models': ['T187', 'T777', 'T787']},
 'Source2.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Stereo', '7.1', 'Off'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source2.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source2.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source2.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['HDMI', 'Off', 'Optical', 'Coaxial', 'ARC'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Digital Audio Format',
                                'models': ['T187', 'T777', 'T787']},
 'Source2.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source2.Enabled': {'op': '=/+/-/?',
                     'values': ['Yes', 'No'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source2.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source2.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source2.VideoFormat': {'op': '=/+/-/?',
                         'values': ['HDMI', 'Video', 'SVideo', 'Off', 'Component'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source2.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source3.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Off', 'Stereo', '7.1'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source3.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source3.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source3.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['ARC', 'Off', 'Optical', 'Coaxial', 'HDMI'],
                                'range': None,
                                'step': None,
                                'desc': "Set source's digital audio to HDMI's audio return c "
                                        'hannel (ARC)',
                                'models': ['T187', 'T777', 'T787']},
 'Source3.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source3.Enabled': {'op': '=/+/-/?',
                     'values': ['No', 'Yes'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source3.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source3.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source3.VideoFormat': {'op': '=/+/-/?',
                         'values': ['Off', 'Video', 'SVideo', 'Component', 'HDMI'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source3.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source4.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['7.1', 'Off', 'Stereo'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source4.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source4.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source4.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['ARC', 'HDMI', 'Coaxial', 'Off', 'Optical'],
                                'range': None,
                                'step': None,
                                'desc': "Set source's digital audio to HDMI's audio return c "
                                        'hannel (ARC)',
                                'models': ['T187', 'T777', 'T787']},
 'Source4.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source4.Enabled': {'op': '=/+/-/?',
                     'values': ['No', 'Yes'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source4.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source4.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source4.VideoFormat': {'op': '=/+/-/?',
                         'values': ['Component', 'Video', 'HDMI', 'Off', 'SVideo'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source4.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source5.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Off', 'Stereo', '7.1'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source5.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source5.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source5.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['HDMI', 'Off', 'Optical', 'Coaxial', 'ARC'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Digital Audio Format',
                                'models': ['T187', 'T777', 'T787']},
 'Source5.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source5.Enabled': {'op': '=/+/-/?',
                     'values': ['Yes', 'No'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source5.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source5.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source5.VideoFormat': {'op': '=/+/-/?',
                         'values': ['Off', 'HDMI', 'Component', 'Video', 'SVideo'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source5.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source6.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Off', 'Stereo', '7.1'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source6.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source6.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source6.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['Coaxial', 'ARC', 'HDMI', 'Off', 'Optical'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Digital Audio Format',
                                'models': ['T187', 'T777', 'T787']},
 'Source6.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source6.Enabled': {'op': '=/+/-/?',
                     'values': ['No', 'Yes'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source6.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source6.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source6.VideoFormat': {'op': '=/+/-/?',
                         'values': ['Off', 'Video', 'SVideo', 'Component', 'HDMI'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source6.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source7.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Off', 'Stereo', '7.1'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source7.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source7.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source7.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['ARC', 'HDMI', 'Coaxial', 'Optical', 'Off'],
                                'range': None,
                                'step': None,
                                'desc': "Set source's digital audio to HDMI's audio return c "
                                        'hannel (ARC)',
                                'models': ['T187', 'T777', 'T787']},
 'Source7.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source7.Enabled': {'op': '=/+/-/?',
                     'values': ['No', 'Yes'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source7.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source7.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source7.VideoFormat': {'op': '=/+/-/?',
                         'values': ['HDMI', 'Component', 'SVideo', 'Video', 'Off'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source7.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source8.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Off', 'Stereo', '7.1'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source8.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source8.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source8.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['Optical', 'ARC', 'Coaxial', 'Off', 'HDMI'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Digital Audio Format',
                                'models': ['T187', 'T777', 'T787']},
 'Source8.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source8.Enabled': {'op': '=/+/-/?',
                     'values': ['No', 'Yes'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source8.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source8.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source8.VideoFormat': {'op': '=/+/-/?',
                         'values': ['Component', 'HDMI', 'Off', 'Video', 'SVideo'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source8.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Source9.AnalogAudioFormat': {'op': '=/+/-/?',
                               'values': ['Stereo', '7.1', 'Off'],
                               'range': None,
                               'step': None,
                               'desc': 'Set Analog Audio Format',
                               'models': ['T187', 'T777', 'T787']},
 'Source9.AnalogAudioInput': {'op': '=/+/-/?',
                              'values': [],
                              'range': [1, 8],
                              'step': 1,
                              'desc': 'Set Analog Audio Input',
                              'models': ['T187', 'T777', 'T787']},
 'Source9.AnalogGain': {'op': '=/+/-/?',
                        'values': [],
                        'range': [-12, 12],
                        'step': 3,
                        'desc': 'Set Analog Audio Gain',
                        'models': ['T187', 'T777', 'T787']},
 'Source9.DigitalAudioFormat': {'op': '=/+/-/?',
                                'values': ['HDMI', 'Coaxial', 'Optical', 'Off', 'ARC'],
                                'range': None,
                                'step': None,
                                'desc': 'Set Digital Audio Format',
                                'models': ['T187', 'T777', 'T787']},
 'Source9.DigitalAudioInput': {'op': '=/+/-/?',
                               'values': [],
                               'range': [1, 8],
                               'step': 1,
                               'desc': 'Set Digital Audio Input',
                               'models': ['T187', 'T777', 'T787']},
 'Source9.Enabled': {'op': '=/+/-/?',
                     'values': ['No', 'Yes'],
                     'range': None,
                     'step': None,
                     'desc': 'Set Source Enabled No/Yes',
                     'models': ['T187', 'T777', 'T787']},
 'Source9.Preset': {'op': '=/+/-/?',
                    'values': [],
                    'range': [0, 5],
                    'step': 1,
                    'desc': 'Set Source Preset',
                    'models': ['T187', 'T777', 'T787']},
 'Source9.TriggerOut': {'op': '=/+/-/?',
                        'values': [],
                        'range': [0, 7],
                        'step': 1,
                        'desc': 'Set Source Trigger Out',
                        'models': ['T187', 'T777', 'T787']},
 'Source9.VideoFormat': {'op': '=/+/-/?',
                         'values': ['SVideo', 'Video', 'Component', 'HDMI', 'Off'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Source Video Format',
                         'models': ['T187', 'T777', 'T787']},
 'Source9.VideoInput': {'op': '=/+/-/?',
                        'values': [],
                        'range': [1, 8],
                        'step': 1,
                        'desc': 'Set Source Video Input',
                        'models': ['T187', 'T777', 'T787']},
 'Tuner.AM.Frequency': {'op': '=/+/-/?',
                        'values': ['String'],
                        'range': None,
                        'step': None,
                        'desc': 'AM Frequency String (ie. "680")',
                        'models': ['T187', 'T777', 'T787']},
 'Tuner.AMStep': {'op': '=/+/-/?',
                  'values': [],
                  'range': [9, 10],
                  'step': 1,
                  'desc': 'Set Tuner AM Step Value',
                  'models': ['T187', 'T777', 'T787']},
 'Tuner.Band': {'op': '=/+/-/?',
                'values': ['AM', 'FM', 'DAB', 'XM'],
                'range': None,
                'step': None,
                'desc': 'Set Tuner Band',
                'models': ['T187', 'T777', 'T787']},
 'Tuner.DAB.DLS': {'op': '?',
                   'values': [],
                   'range': None,
                   'step': None,
                   'desc': 'DAB DLS Text',
                   'models': ['T187', 'T777', 'T787']},
 'Tuner.DAB.Service': {'op': '?',
                       'values': [],
                       'range': None,
                       'step': None,
                       'desc': 'DAB Service Name',
                       'models': ['T187', 'T777', 'T787']},
 'Tuner.DigitalMode': {'op': '=/+/-/?',
                       'values': ['DAB', 'XM'],
                       'range': None,
                       'step': None,
                       'desc': 'Set Digital Mode (C Version)',
                       'models': ['T187', 'T777', 'T787']},
 'Tuner.FM.Frequency': {'op': '=/+/-/?',
                        'values': ['String'],
                        'range': None,
                        'step': None,
                        'desc': 'FM Frequency String (ie. "102.1")',
                        'models': ['T187', 'T777', 'T787']},
 'Tuner.FM.Mute': {'op': '=/+/-/?',
                   'values': ['Off', 'On'],
                   'range': None,
                   'step': None,
                   'desc': 'Set Tuner FM Mute On/Off',
                   'models': ['T187', 'T777', 'T787']},
 'Tuner.FM.RDSName': {'op': '?',
                      'values': [],
                      'range': None,
                      'step': None,
                      'desc': 'FM RDS Name',
                      'models': ['T187', 'T777', 'T787']},
 'Tuner.FM.RDSText': {'op': '?',
                      'values': [],
                      'range': None,
                      'step': None,
                      'desc': 'FM RDS Text',
                      'models': ['T187', 'T777', 'T787']},
 'Tuner.Preset': {'op': '=/+/-/?',
                  'values': [],
                  'range': [1, 40],
                  'step': 1,
                  'desc': 'Set Tuner Preset',
                  'models': ['T187', 'T777', 'T787']},
 'Tuner.XM.Channel': {'op': '=/+/-/?',
                      'values': [],
                      'range': [0, 255],
                      'step': 1,
                      'desc': 'XM Channel Number',
                      'models': ['T187', 'T777', 'T787']},
 'Tuner.XM.ChannelName': {'op': '?',
                          'values': [],
                          'range': None,
                          'step': None,
                          'desc': 'XM Channel Name',
                          'models': ['T187', 'T777', 'T787']},
 'Tuner.XM.Name': {'op': '?',
                   'values': [],
                   'range': None,
                   'step': None,
                   'desc': 'XM Song name',
                   'models': ['T187', 'T777', 'T787']},
 'Tuner.XM.Title': {'op': '?',
                    'values': [],
                    'range': None,
                    'step': None,
                    'desc': 'XM Song Title',
                    'models': ['T187', 'T777', 'T787']},
 'UART.Version': {'op': '?',
                  'values': [],
                  'range': None,
                  'step': None,
                  'desc': 'Query UART Version',
                  'models': ['T187', 'T777', 'T787']},
 'Zone2.Mute': {'op': '=/+/-/?',
                'values': ['On', 'Off'],
                'range': None,
                'step': None,
                'desc': 'Set Zone Mute',
                'models': ['T187', 'T777', 'T787']},
 'Zone2.Power': {'op': '=/+/-/?',
                 'values': ['Off', 'On'],
                 'range': None,
                 'step': None,
                 'desc': 'Set Zone Power',
                 'models': ['T187', 'T777', 'T787']},
 'Zone2.Source': {'op': '=/+/-/?',
                  'values': [],
                  'range': [1, 11],
                  'step': 1,
                  'desc': 'Set Zone Source',
                  'models': ['T187', 'T777', 'T787']},
 'Zone2.Volume': {'op': '=/+/-/?',
                  'values': [],
                  'range': [-99, 19],
                  'step': 1,
                  'desc': 'Set Zone Volume',
                  'models': ['T187', 'T777', 'T787']},
 'Zone2.VolumeControl': {'op': '=/+/-/?',
                         'values': ['Fixed', 'Variable'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Zone Volume Control Variable/Fixed',
                         'models': ['T187', 'T777', 'T787']},
 'Zone2.VolumeFixed': {'op': '=/+/-/?',
                       'values': [],
                       'range': [-95, 16],
                       'step': 1,
                       'desc': 'Set Zone Fixed Volume Value',
                       'models': ['T187', 'T777', 'T787']},
 'Zone3.Mode': {'op': '=/+/-/?',
                'values': ['Record', 'Zone'],
                'range': None,
                'step': None,
                'desc': 'Set Zone Mode Zone/Record',
                'models': ['T187', 'T777', 'T787']},
 'Zone3.Mute': {'op': '=/+/-/?',
                'values': ['Off', 'On'],
                'range': None,
                'step': None,
                'desc': 'Set Zone Mute',
                'models': ['T187', 'T777', 'T787']},
 'Zone3.Power': {'op': '=/+/-/?',
                 'values': ['On', 'Off'],
                 'range': None,
                 'step': None,
                 'desc': 'Set Zone Power',
                 'models': ['T187', 'T777', 'T787']},
 'Zone3.Source': {'op': '=/+/-/?',
                  'values': [],
                  'range': [1, 11],
                  'step': 1,
                  'desc': 'Set Zone Source',
                  'models': ['T187', 'T777', 'T787']},
 'Zone3.Volume': {'op': '=/+/-/?',
                  'values': [],
                  'range': [-99, 19],
                  'step': 1,
                  'desc': 'Set Zone Volume',
                  'models': ['T187', 'T777', 'T787']},
 'Zone3.VolumeControl': {'op': '=/+/-/?',
                         'values': ['Variable', 'Fixed'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Zone Volume Control Variable/Fixed',
                         'models': ['T187', 'T777', 'T787']},
 'Zone3.VolumeFixed': {'op': '=/+/-/?',
                       'values': [],
                       'range': [-95, 16],
                       'step': 1,
                       'desc': 'Set Zone Fixed Volume',
                       'models': ['T187', 'T777', 'T787']},
 'Zone4.Mode': {'op': '=/+/-/?',
                'values': ['Zone', 'Record'],
                'range': None,
                'step': None,
                'desc': 'Set Zone Mode Zone/Record',
                'models': ['T187', 'T777', 'T787']},
 'Zone4.Mute': {'op': '=/+/-/?',
                'values': ['On', 'Off'],
                'range': None,
                'step': None,
                'desc': 'Set Zone Mute',
                'models': ['T187', 'T777', 'T787']},
 'Zone4.Power': {'op': '=/+/-/?',
                 'values': ['On', 'Off'],
                 'range': None,
                 'step': None,
                 'desc': 'Set Zone Power',
                 'models': ['T187', 'T777', 'T787']},
 'Zone4.Source': {'op': '=/+/-/?',
                  'values': [],
                  'range': [1, 11],
                  'step': 1,
                  'desc': 'Set Zone Source',
                  'models': ['T187', 'T777', 'T787']},
 'Zone4.Volume': {'op': '=/+/-/?',
                  'values': [],
                  'range': [-99, 19],
                  'step': 1,
                  'desc': 'Set Zone Volume',
                  'models': ['T187', 'T777', 'T787']},
 'Zone4.VolumeControl': {'op': '=/+/-/?',
                         'values': ['Variable', 'Fixed'],
                         'range': None,
                         'step': None,
                         'desc': 'Set Zone Volume Control Variable/Fixed',
                         'models': ['T187', 'T777', 'T787']},
 'Zone4.VolumeFixed': {'op': '=/+/-/?',
                       'values': [],
                       'range': [-95, 16],
                       'step': 1,
                       'desc': 'Set Zone Fixed Volume',
                       'models': ['T187', 'T777', 'T787']}}

QUERYABLE_VARIABLES = [
    variable for variable, meta in COMMANDS.items() if "?" in meta["op"]
]
SETTABLE_VARIABLES = [
    variable for variable, meta in COMMANDS.items() if "=" in meta["op"]
]
STEPPABLE_VARIABLES = [
    variable for variable, meta in COMMANDS.items() if "+" in meta["op"] or "-" in meta["op"]
]
